### ISSUE TITLE
Ensure sequalizer is assigning pool and settings for connections

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/sequelizer#7]
As described in the following bug report from Amgen (https://github.com/outcomesinsights/amgen_jigsaw_external/issues/119) studies were failing due to connections not being assigned to the jigsaw.tst pool. When study queries are sent, they do not use the same connection for the entire process. In some instances, new connections, with wrong pool assignments, are being assigned to study queries which cause the studies to fail.

**Comment by aguynamedryan** [comment]
Sequel provides a beautiful, transparent connection pooling mechanism.  It's so transparent, I barely knew it was there.

Sequelizer naively setup proper session-level variables (e.g. resource_pool) on the connection that Sequel returns, but that connection is only the first of many possible connections made available through Sequel's connection pool.

Subsequent connections made in the same pool would not go through the same session-level variable assignment.

Sequelizer now properly uses the "after_connect" option in Sequel so that each connection created in the pool will have the appropriate session-level settings applied before the connection is used by the calling program (e.g. ConceptQL).
